ThreeBoxes/Box/main/default/objects/Box__c/Box__c.object-meta.xml
<CustomObject>
    <label>Box</label>
    <nameField>
        <label>Box名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ThreeBoxes/Box/main/default/objects/Box__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

ThreeBoxes/Box/main/default/objects/Box__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Move</label>
    <type>Checkbox</type>
</CustomField>

ThreeBoxes/Box/main/default/classes/BoxManager.cls
@RestResource(urlMapping='/Box/*')
global with sharing class BoxManager {
    @HttpGet
    global static Box__c GetBoxById() {
        RestRequest request = RestContext.request;
        String boxIdStr = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        Decimal boxId = Decimal.valueOf(boxIdStr);

        Box__c box = [SELECT Id__c, Name, Move__c FROM Box__c WHERE Id__c = :boxId];
        
        return box;
    }

    @HttpPatch
    global static Map<String, Boolean> PatchBoxById() {
        Map<String, Boolean> success = new Map<String, Boolean>();
        success.put('success', false);
        RestRequest request = RestContext.request;
        String boxIdStr = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        Decimal boxId = Decimal.valueOf(boxIdStr);
        
        Box__c thisBox = [SELECT Id__c, Name, Move__c FROM Box__c WHERE Id__c = :boxId];
        
        Map<String, Object> params = (Map<String, Object>)JSON.deserializeUntyped(request.requestbody.tostring());
        System.debug(params);
        Boolean move = (Boolean)(params.get('Move__c'));
        if (move != null) {
            thisBox.Move__c = move;
            update thisBox;
            success.put('success', true);
            success.put('Move__c', move);
        }
        return success;
    }
}