ThreeBoxes/Box/main/default/objects/Box__c/Box__c.object-meta.xml
<CustomObject>
    <label>Box</label>
    <nameField>
        <label>Box名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ThreeBoxes/Box/main/default/objects/Box__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

ThreeBoxes/Box/main/default/objects/Box__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Move</label>
    <type>Checkbox</type>
</CustomField>

box/force-app/main/default/classes/BoxController.cls
public with sharing class BoxController {
    @AuraEnabled(cacheable=false)
    public static List<Box__c> getBoxes() {
        List<Box__c> boxes = [SELECT Id, Id__c, Name, Move__c FROM Box__c];
        //for (Box__c b : boxes) {
        //    System.debug(b.Name);
        //}
        return boxes;
    }

    @AuraEnabled(cacheable=false)
    public static void moveBox(Integer id, Boolean move){
        Box__c box = [SELECT Id, Id__c, Name, Move__c FROM Box__c WHERE Id__c = :id];
        box.Move__c = move;
        update box;
    }
}