ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/BoxCounterApiService__c.object-meta.xml
<CustomObject>
    <label>BoxCounterApiService</label>
    <nameField>
        <label>BoxCounterApiService名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

ThreeBoxes/Box/main/default/classes/CalloutToHeroku.cls
public with sharing class CalloutToHeroku {

    @future(callout=true)
    public static void incrementCounter(Decimal id) {
        BoxCounterApiService__c cred = getCred();
        HttpRequest request = new HttpRequest();
        request.setEndPoint(cred.Endpoint__c + 'box/' + id + '/count');
        request.setMethod('PATCH');
        Blob headerValue = Blob.valueOf(cred.Username__c + ':' + cred.Password__c);
        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        request.setHeader('Authorization', authorizationHeader);   
        HttpResponse response = new HTTP().send(request);
    }

    @future(callout=true)
    public static void resetCounter() {
        BoxCounterApiService__c cred = getCred();
        HttpRequest request = new HttpRequest();
        request.setEndPoint(cred.Endpoint__c + 'reset');
        request.setMethod('PATCH');
        Blob headerValue = Blob.valueOf(cred.Username__c + ':' + cred.Password__c);
        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        request.setHeader('Authorization', authorizationHeader);   
        HttpResponse response = new HTTP().send(request);
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        BoxCounterApiService__c boxCounterApiService = [SELECT Email__c FROM BoxCounterApiService__c WHERE Name = 'Heroku'];
        String[] toAddresses = new String[]{boxCounterApiService.Email__c};
        mail.setToAddresses(toAddresses);
		mail.setSubject('Box stats reset');
        Datetime today = Date.today();
		mail.setPlainTextBody('Box counters reset at ' + today);
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
    }

    public static BoxCounterApiService__c getCred() {
        return [SELECT EndPoint__c, Username__c, Password__c FROM BoxCounterApiService__c WHERE Name = 'Heroku'];
    }
}