ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/BoxCounterApiService__c.object-meta.xml
<CustomObject>
    <label>BoxCounterApiService</label>
    <nameField>
        <label>BoxCounterApiService名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

ThreeBoxes/Box/main/default/objects/BoxCounterApiService__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

connected_app/apex/force-app/main/default/classes/BoxStatsForLWC.cls
public with sharing class BoxStatsForLWC {

    @AuraEnabled(cacheable=false)
    public static List<BoxStats> getStatsFromHeroku(){
        try {
            BoxCounterApiService__c cred = CalloutToHeroku.getCred();
            HttpRequest request = new HttpRequest();
            request.setEndPoint(cred.Endpoint__c + 'stats');
            request.setMethod('GET');
            Blob headerValue = Blob.valueOf(cred.Username__c + ':' + cred.Password__c);
            String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
            request.setHeader('Authorization', authorizationHeader);  
            request.setHeader('Accept', 'application/json'); 
            HttpResponse response = new HTTP().send(request);
            String body = response.getBody();
            List<BoxStats> statsList = BoxStats.parse(body);
            System.debug(statsList);
            return statsList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}